#!/bin/bash

mkdir data
wget https://surfdrive.surf.nl/files/index.php/s/7RvP2iYCOXkcWRp/download
mv download fiqh-i10-s100-w5-sg0_wv.zip
wget https://surfdrive.surf.nl/files/index.php/s/Ah9HeEg8vDMzPIo/download
mv download stemmed-fiqh-i10-s100-w5-sg0_wv.zip
wget https://archive.org/download/aravec2.0/wiki_cbow_100.zip
python -c "import zipfile; zipfile.ZipFile('wiki_cbow_100.zip','r').extractall('data')"
python -c "import zipfile; zipfile.ZipFile('fiqh-i10-s100-w5-sg0_wv.zip','r').extractall('data')"
python -c "import zipfile; zipfile.ZipFile('stemmed-fiqh-i10-s100-w5-sg0_wv.zip','r').extractall('data')"
rm wiki_cbow_100.zip fiqh-i10-s100-w5-sg0_wv.zip stemmed-fiqh-i10-s100-w5-sg0_wv.zip
