#!/bin/bash

mkdir data
wget https://surfdrive.surf.nl/files/index.php/s/AZLwqFhRE7WN9cB/download
wget https://archive.org/download/aravec2.0/wiki_cbow_100.zip
python -c "import zipfile; zipfile.ZipFile('wiki_cbow_100.zip','r').extractall('data')"
python -c "import zipfile; zipfile.ZipFile('cbow-fiqh-100-wikipedia-finetuned.zip','r').extractall('data')"
rm wiki_cbow_100.zip cbow-fiqh-100-wikipedia-finetuned.zip
